"""Transport-independent building blocks for the Robot LLM experiment."""

from .agent_loop import (
    ClosedLoopAgent,
    DecisionProposal,
    EpisodeResult,
    LoopLimits,
    MotorPositionGoal,
    PlanningContext,
    ProposalError,
    decode_decision_proposal,
)
from .commentary import (
    DEFAULT_OBSTACLE_GATE_POLICY,
    DEFAULT_PROXIMITY_THRESHOLDS,
    ObstacleEvidenceGate,
    ObstacleGatePolicy,
    ProximityObservation,
    ProximityThresholds,
    StableZoneTracker,
    classify_infrared,
    fallback_comment,
    validate_generated_comment,
)
from .contract import CommandResult, MotionCommand, MotorState, RobotState
from .lm_studio import (
    LMStudioError,
    ModelCandidate,
    NativeLMStudioClient,
)
from .robot_api import (
    ActionContext,
    ActionReceipt,
    CapabilityGate,
    ControllerCapabilities,
    MotionRequest,
    MotorCapability,
    ObservationEnvelope,
    RobotActionRejected,
    RobotAPI,
    RobotAPIContractError,
    RobotAPIError,
    SimulatedRobotAPI,
    StopRequest,
)
from .safety import SafetyLimits, SafetyPolicy, SafetyViolation
from .shadow_commentary import (
    ShadowCommentResult,
    ShadowSpeechError,
    run_shadow_comment,
)
from .simulated_robot import SimulatedRobot
from .supervisor_transport import (
    SupervisorRemoteError,
    SupervisorSSHChannelPoisonedError,
    SupervisorSSHConfigurationError,
    SupervisorSSHError,
    SupervisorSSHProtocolError,
    SupervisorSSHSession,
    SupervisorSSHTimeoutError,
    SupervisorSSHTransportError,
    run_motion_free_supervisor_preflight,
)

__all__ = [
    "ActionContext",
    "ActionReceipt",
    "CapabilityGate",
    "ClosedLoopAgent",
    "CommandResult",
    "ControllerCapabilities",
    "DecisionProposal",
    "EpisodeResult",
    "LoopLimits",
    "MotionCommand",
    "MotionRequest",
    "MotorCapability",
    "MotorPositionGoal",
    "MotorState",
    "ObservationEnvelope",
    "PlanningContext",
    "ProposalError",
    "RobotState",
    "RobotActionRejected",
    "RobotAPI",
    "RobotAPIContractError",
    "RobotAPIError",
    "LMStudioError",
    "ModelCandidate",
    "NativeLMStudioClient",
    "DEFAULT_OBSTACLE_GATE_POLICY",
    "DEFAULT_PROXIMITY_THRESHOLDS",
    "ObstacleEvidenceGate",
    "ObstacleGatePolicy",
    "ProximityObservation",
    "ProximityThresholds",
    "SafetyLimits",
    "SafetyPolicy",
    "SafetyViolation",
    "ShadowCommentResult",
    "ShadowSpeechError",
    "SimulatedRobot",
    "SimulatedRobotAPI",
    "StopRequest",
    "SupervisorRemoteError",
    "SupervisorSSHChannelPoisonedError",
    "SupervisorSSHConfigurationError",
    "SupervisorSSHError",
    "SupervisorSSHProtocolError",
    "SupervisorSSHSession",
    "SupervisorSSHTimeoutError",
    "SupervisorSSHTransportError",
    "StableZoneTracker",
    "classify_infrared",
    "decode_decision_proposal",
    "fallback_comment",
    "run_shadow_comment",
    "run_motion_free_supervisor_preflight",
    "validate_generated_comment",
]
