"""Stable public import surface for canonical physical-agent contracts.

Implementations live in focused private modules.  Re-exporting their original
objects here keeps callers decoupled from the internal layout.
"""

from typing import Optional, Tuple

from ._physical_agent_core import (
    ActiveIntent,
    AgentPhase,
    ControllerKey,
    DetourSide,
    DetourTargetIntent,
    ExecutionPlan,
    FollowDirectionIntent,
    GoalAssignment,
    GoalOutcome,
    GoalTerminal,
    IntentPayload,
    IntentPolicy,
    IntentProgress,
    MAX_INT,
    MAX_PLANNING_TICKET_TTL_MS,
    NavigationBasis,
    PhysicalAgentStateError,
    PlanBinding,
    PlanStep,
    PlanningCause,
    PlanningTicket,
    PRIMITIVE_ACTIONS,
    PrimitiveStep,
    SENSOR_OPERATIONS,
    ScanTargetIntent,
    SensorStep,
    WaypointStep,
    _identifier,
    _integer,
    _text,
)
from ._physical_agent_dispatch_contract import (
    ActiveDispatch,
    ControllerCommandReceipt,
    MAX_STEP_COMMAND_SETTLE_MS,
    MAX_STEP_COMMAND_START_TTL_MS,
    PlanStepKey,
    ReceiptOutcome,
    StepCommandAuthorization,
    StepDisposition,
)
from ._physical_agent_events import (
    GoalActivated,
    GoalCompletionRequested,
    IntentAccepted,
    NavigationBasisUpdated,
    PhysicalAgentEvent,
    PlanRecompiled,
    PlanningAbortRequested,
    PlanningHeld,
    PlanningRequested,
    PlanningTicketConsumed,
    PlanningTicketExpired,
    ReplanRequested,
    StopRequested,
    StopVerified,
    StepCommandAuthorized,
    StepCommandDispatched,
    StepCommandRevoked,
    StepCommandSettlementExpired,
    StepCommandSettled,
    TerminalCleared,
)
from ._physical_agent_snapshot import PhysicalAgentState


__all__ = (
    "ActiveIntent",
    "ActiveDispatch",
    "AgentPhase",
    "ControllerKey",
    "ControllerCommandReceipt",
    "DetourSide",
    "DetourTargetIntent",
    "ExecutionPlan",
    "FollowDirectionIntent",
    "GoalActivated",
    "GoalAssignment",
    "GoalCompletionRequested",
    "GoalOutcome",
    "GoalTerminal",
    "IntentAccepted",
    "IntentPolicy",
    "IntentProgress",
    "MAX_PLANNING_TICKET_TTL_MS",
    "MAX_STEP_COMMAND_SETTLE_MS",
    "MAX_STEP_COMMAND_START_TTL_MS",
    "NavigationBasis",
    "NavigationBasisUpdated",
    "PhysicalAgentEvent",
    "PhysicalAgentState",
    "PhysicalAgentStateError",
    "PlanBinding",
    "PlanRecompiled",
    "PlanStep",
    "PlanStepKey",
    "PlanningAbortRequested",
    "PlanningCause",
    "PlanningHeld",
    "PlanningRequested",
    "PlanningTicket",
    "PlanningTicketConsumed",
    "PlanningTicketExpired",
    "PrimitiveStep",
    "ReceiptOutcome",
    "ReplanRequested",
    "ScanTargetIntent",
    "SensorStep",
    "StopRequested",
    "StopVerified",
    "StepCommandAuthorization",
    "StepCommandAuthorized",
    "StepCommandDispatched",
    "StepCommandRevoked",
    "StepCommandSettlementExpired",
    "StepCommandSettled",
    "StepDisposition",
    "TerminalCleared",
    "WaypointStep",
)

# Preserve the historical public class paths as well as object identity.
for _export_name in __all__:
    _export = globals()[_export_name]
    if isinstance(_export, type):
        _export.__module__ = __name__
del _export, _export_name
